import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Themes.colors.white,
  },
  childContainer: {
    flex: 1,
    paddingHorizontal: ScreenUtils.scale(20),
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  separator: {
    height: ScreenUtils.scale(1),
    backgroundColor: Themes.colors.colGray20,
    marginHorizontal: ScreenUtils.scale(20),
    marginVertical: ScreenUtils.scale(24),
  },
  transactionHistoryLabel: {
    ...Themes.font.bold,
    fontSize: 16,
    color: Themes.colors.black,
  },
  searchView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  filter: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.primary,
  },
  searchContainer: {
    marginVertical: ScreenUtils.scale(26),
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: ScreenUtils.scale(20),
    marginBottom: ScreenUtils.scale(20),
  },
  textHeader: {
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
    fontSize: 18,
  },
  headerButton: {
    height: ScreenUtils.scale(40),
    justifyContent: "center",
    alignItems: "center",
  },
  textHeaderRight: {
    ...Themes.font.medium,
    color: Themes.colors.primary,
    fontSize: 14,
  },
  contentFilter: {
    paddingHorizontal: ScreenUtils.scale(20),
    paddingBottom: ScreenUtils.scale(20),
  },
  titleGroupFilter: {
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
    fontSize: 14,
  },
  showMore: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Themes.colors.colGray10,
    marginHorizontal: ScreenUtils.scale(40),
    marginVertical: ScreenUtils.scale(12),
    paddingVertical: ScreenUtils.scale(9),
    borderRadius: ScreenUtils.scale(18),
  },
  buttonText: {
    ...Themes.font.medium,
    fontSize: 12,
    color: Themes.colors.coolGray60,
    lineHeight: ScreenUtils.scale(18),
  },
  separatorHorizontal: {
    height: ScreenUtils.scale(1),
    backgroundColor: Themes.colors.colGray20,
    marginVertical: ScreenUtils.scale(24),
  },
  pickOption: {
    width: "48%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Themes.colors.colGray10,
    borderRadius: ScreenUtils.scale(11),
    paddingVertical: ScreenUtils.scale(9),
    marginTop: ScreenUtils.scale(12),
  },
  rightModal: {
    backgroundColor: Themes.colors.white,
    margin: 0,
    flex: 1,
    justifyContent: "flex-end",
  },
  transactionItem: {
    flexDirection: "column",
    justifyContent: "center",
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(10),
  },
  transactionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: ScreenUtils.scale(6),
  },
  transactionOrderPayment: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  spaceBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: ScreenUtils.scale(4),
  },
  orderPaymentImage: {
    width: ScreenUtils.scale(40),
    height: ScreenUtils.scale(40),
    marginRight: ScreenUtils.scale(12),
  },
  flex1: {
    flex: 1,
  },
  iconPayment: {
    width: ScreenUtils.scale(24),
    height: ScreenUtils.scale(24),
    marginRight: ScreenUtils.scale(8),
  },
  transactionSource: {
    ...Themes.font.semiBold,
    fontSize: 12,
    color: Themes.colors.coolGray100,
  },
  transactionStatus: {
    ...Themes.font.medium,
    fontSize: 12,
    color: Themes.colors.coolGray60,
  },
  transactionInfo: {
    ...Themes.font.medium,
    fontSize: 12,
    color: Themes.colors.coolGray60,
  },
  transactionAmount: {
    ...Themes.font.currency,
    fontSize: 14,
    color: Themes.colors.success60,
  },
  transactionRef: {
    ...Themes.font.medium,
    fontSize: 12,
    color: Themes.colors.coolGray100,
  },
  rangeDate: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: ScreenUtils.scale(24),
  },
  inputDate: {
    flex: 0.48,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  inputDateTitle: {
    ...Themes.font.medium,
    fontSize: 12,
    color: Themes.colors.coolGray60,
  },
  inputDateButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: Themes.colors.coolGray,
    paddingVertical: ScreenUtils.scale(7),
  },
  inputDateText: {
    ...Themes.font.medium,
    fontSize: 16,
    color: Themes.colors.textPrimary,
  },
  rangeDateText: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.textPrimary,
    marginTop: ScreenUtils.scale(24),
  },
  wrapView: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  headerWallet: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: ScreenUtils.scale(16),
  },
  tabView: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  activeTab: {
    height: ScreenUtils.scale(4),
    backgroundColor: Themes.colors.primary,
    width: "100%",
    borderTopLeftRadius: ScreenUtils.scale(4),
    borderTopRightRadius: ScreenUtils.scale(4),
    marginTop: ScreenUtils.scale(8),
  },
  activeTabText: {
    ...Themes.font.medium,
    fontSize: 14,
    fontWeight: "700",
    color: Themes.colors.coolGray100,
  },
  nonActiveTabText: {
    ...Themes.font.medium,
    fontSize: 14,
    fontWeight: "500",
    color: Themes.colors.coolGray60,
  },
  pointInfoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: ScreenUtils.scale(24),
  },
  labelInfo: {
    ...Themes.font.medium,
    fontSize: 12,
    fontWeight: "400",
    color: Themes.colors.textPrimary,
    lineHeight: ScreenUtils.scale(18),
  },
  availablePoint: {
    ...Themes.font.currency,
    fontSize: 24,
    fontWeight: "500",
    color: Themes.colors.textPrimary,
    lineHeight: ScreenUtils.scale(36),
  },
  pointView: {
    flexDirection: "column",
    paddingHorizontal: ScreenUtils.scale(16),
  },
  holdPointContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: ScreenUtils.scale(13),
    paddingBottom: ScreenUtils.scale(24),
  },
  holdPointInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  orderNote: {
    ...Themes.font.currency,
    fontSize: 12,
    fontWeight: "400",
    color: Themes.colors.textPrimary,
    flex: 1,
  },
  headerPaymentDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: ScreenUtils.scale(16),
  },
  headerPaymentText: {
    ...Themes.font.medium,
    fontSize: 18,
    lineHeight: 27,
    fontWeight: "700",
    color: Themes.colors.coolGray100,
    maxWidth: 200,
  },
  hView: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  statusContainer: {
    backgroundColor: Themes.colors.primary,
    height: ScreenUtils.scale(24),
    paddingHorizontal: ScreenUtils.scale(12),
    borderRadius: ScreenUtils.scale(30),
    marginLeft: ScreenUtils.scale(16),
    justifyContent: "center",
    alignItems: "center",
  },
  status: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: Themes.colors.white,
  },
  createDate: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "400",
    color: Themes.colors.coolGray60,
  },
  content: {
    flexDirection: "column",
    paddingHorizontal: ScreenUtils.scale(16),
    marginTop: ScreenUtils.scale(8),
  },
  paymentInfo: {
    ...Themes.font.medium,
    fontSize: 18,
    fontWeight: "500",
    color: Themes.colors.coolGray100,
    lineHeight: 27,
    marginVertical: ScreenUtils.scale(12),
  },
  paymentData: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    color: Themes.colors.coolGray100,
    marginTop: ScreenUtils.scale(4),
    marginBottom: ScreenUtils.scale(12),
  },
  amountTitle: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
    color: Themes.colors.coolGray60,
  },
  amount: {
    ...Themes.font.currency,
    fontSize: 20,
    lineHeight: 30,
    fontWeight: "500",
  },
  amountContainer: {
    backgroundColor: Themes.colors.colGray10,
    paddingVertical: ScreenUtils.scale(12),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: ScreenUtils.scale(8),
  },
  transactionCode: {
    ...Themes.font.medium,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
    color: Themes.colors.coolGray100,
  },
});
