import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { Dimensions, StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Themes.colors.white,
  },
  header: {
    marginTop: ScreenUtils.scale(20),
    height: 35,
    borderBottomWidth: 1,
    borderColor: Themes.colors.colGray10,
  },
  itemHeader: {
    paddingHorizontal: ScreenUtils.scale(20),
  },
  textItemHeader: {
    color: Themes.colors.coolGray60,
    fontSize: 13,
    lineHeight: 19.5,
    ...Themes.font.medium,
  },
  content: {
    paddingHorizontal: ScreenUtils.scale(20),
  },
  textHeader: {
    color: Themes.colors.coolGray60,
    fontSize: 14,
    ...Themes.font.regular,
    lineHeight: 21,
  },
  flexRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  titleHeader: {
    fontSize: 14,
    ...Themes.font.bold,
    lineHeight: 21,
    color: Themes.colors.coolGray100,
    marginLeft: ScreenUtils.scale(8),
    maxWidth: ScreenUtils.WIDTH_SCREEN / 2,
  },
  itemPaymentMethod: {},
  headerItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  contentItemPay: {
    paddingLeft: ScreenUtils.scale(20),
  },
  iconLogoVisa: {
    height: ScreenUtils.scale(16),
    width: ScreenUtils.scale(52),
    marginVertical: ScreenUtils.scale(16),
  },
  iconLogoAmex: {
    height: ScreenUtils.scale(16),
    width: ScreenUtils.scale(24),
    marginLeft: ScreenUtils.scale(16),
    marginVertical: ScreenUtils.scale(16),
  },
  iconLogoMasterCard: {
    height: ScreenUtils.scale(16),
    width: ScreenUtils.scale(26),
    marginLeft: ScreenUtils.scale(16),
    marginVertical: ScreenUtils.scale(16),
  },
  br: {
    height: 1,
    width: "100%",
    backgroundColor: Themes.colors.colGray20,
    marginTop: ScreenUtils.scale(24),
  },
  iconLogoPayPal: {
    height: ScreenUtils.scale(16),
    width: ScreenUtils.scale(65),
    marginLeft: ScreenUtils.scale(25),
    marginTop: ScreenUtils.scale(8),
  },
  textItemPaypal: {
    color: Themes.colors.coolGray60,
    fontSize: 14,
    ...Themes.font.regular,
    lineHeight: 21,
    marginTop: ScreenUtils.scale(16),
  },
  titleInputDeposit: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.textPrimary,
    fontWeight: "700",
    marginTop: ScreenUtils.scale(24),
  },
  textInput: {
    width: "95%",
    color: Themes.colors.textPrimary,
    fontSize: 14,
    ...Themes.font.regular,
    lineHeight: 21,
  },
  inputLayer: {
    width: "100%",
    height: ScreenUtils.scale(40),
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: Themes.colors.collGray40,
    flexDirection: "row",
    paddingRight: ScreenUtils.scale(5),
  },
  optionsIcon: {},
  textNote: {
    fontSize: 12,
    lineHeight: 24,
    color: Themes.colors.coolGray60,
    ...Themes.font.regular,
    marginTop: ScreenUtils.scale(8),
  },
  listMoney: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: ScreenUtils.scale(24),
    marginBottom: ScreenUtils.scale(48),
  },
  itemPrice: {
    height: ScreenUtils.scale(40),
    paddingHorizontal: ScreenUtils.scale(16),
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: 20,
    marginRight: ScreenUtils.scale(8),
  },
  valuePrice: {
    color: Themes.colors.textPrimary,
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.semiBold,
  },
  buttonSubMit: {
    height: ScreenUtils.scale(40),
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Themes.colors.primary,
    borderRadius: 20,
  },
  textSubmit: {
    fontSize: 14,
    lineHeight: 24,
    ...Themes.font.semiBold,
    color: Themes.colors.white,
  },
  textSelectBank: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
    marginLeft: ScreenUtils.scale(25),
    marginTop: ScreenUtils.scale(16),
  },
  iconBank: {
    height: ScreenUtils.scale(24),
    width: ScreenUtils.scale(70),
  },
  contentItemBank: {
    marginTop: ScreenUtils.scale(16),
  },
  textItemBank: {
    fontSize: 12,
    lineHeight: 18,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
    marginLeft: ScreenUtils.scale(21),
    marginTop: ScreenUtils.scale(5),
  },
  contentOptionBank: {},
  headerItemBank: {
    flexDirection: "row",
    width: "100%",
  },
  textContentBank: {
    fontSize: 12,
    lineHeight: 18,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
    marginLeft: ScreenUtils.scale(25),
    marginTop: ScreenUtils.scale(16),
  },
  contentInputInfo: {
    marginBottom: ScreenUtils.scale(15),
  },
  titleItemInfo: {
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.textPrimary,
    ...Themes.font.bold,
  },
  inpuInfo: {
    color: Themes.colors.textPrimary,
    fontSize: 16,
    ...Themes.font.regular,
    lineHeight: 24,
  },
  note: {
    flexDirection: "row",
    marginBottom: ScreenUtils.scale(48),
  },
  noteLeft: {
    width: 10,
    alignItems: "center",
  },
  textNotePayBank: {
    fontSize: 12,
    lineHeight: 24,
    color: Themes.colors.coolGray60,
    ...Themes.font.regular,
  },
  notedot: {
    fontSize: 16,
    lineHeight: 28,
    color: Themes.colors.coolGray60,
    ...Themes.font.bold,
    marginTop: ScreenUtils.scale(-5),
  },
  flexModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: ScreenUtils.scale(49),
  },
  contentModal: {
    width: "100%",
    borderRadius: 16,
    paddingHorizontal: ScreenUtils.scale(24),
    paddingVertical: ScreenUtils.scale(24),
    backgroundColor: Themes.colors.white,
    alignItems: "center",
  },
  viewTrue: {
    height: ScreenUtils.scale(80),
    width: ScreenUtils.scale(80),
    borderRadius: 80,
    borderWidth: 2,
    borderColor: Themes.colors.green22,
    justifyContent: "center",
    alignItems: "center",
    marginTop: ScreenUtils.scale(28),
  },
  titleModal: {
    color: Themes.colors.textPrimary,
    fontSize: 16,
    ...Themes.font.bold,
    lineHeight: 24,
    marginTop: ScreenUtils.scale(24),
    textAlign: "center",
  },
  textModal: {
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.coolGray60,
    ...Themes.font.regular,
    marginTop: ScreenUtils.scale(16),
  },
  iconCloseModal: {
    position: "absolute",
    right: 18,
    top: 18,
    zIndex: 2,
  },
  textAdd: {
    fontSize: 14,
    lineHeight: 21,
    color: Themes.colors.primary,
    ...Themes.font.regular,
    marginTop: ScreenUtils.scale(16),
  },
  inputCreditLayer: {
    width: "100%",
    height: ScreenUtils.scale(40),
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    paddingHorizontal: ScreenUtils.scale(16),
    marginTop: ScreenUtils.scale(10),
  },
  textInputCredit: {
    width: "100%",
    fontSize: 14,
    lineHeight: 21,
    color: Themes.colors.textPrimary,
    ...Themes.font.medium,
  },
  iconRight: {
    position: "absolute",
    right: ScreenUtils.scale(10),
    top: ScreenUtils.scale(7),
  },
  contentInputCredit: {
    marginTop: ScreenUtils.scale(24),
    paddingRight: ScreenUtils.scale(20),
  },
  flexCvv: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: ScreenUtils.scale(26),
  },
  itemLeft: {
    width: "50%",
  },
  textCurrent: {
    fontSize: 14,
    lineHeight: 21,
    color: Themes.colors.textPrimary,
    ...Themes.font.regular,
  },
  selectItem: {
    height: 16,
    width: 16,
    backgroundColor: Themes.colors.white,
    borderColor: Themes.colors.coolGray60,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: ScreenUtils.scale(8),
  },
  textRemember: {
    lineHeight: 19.5,
    fontSize: 13,
    ...Themes.font.regular,
    color: Themes.colors.textPrimary,
  },
  provider: {
    flexDirection: "row",
    alignSelf: "flex-end",
    marginTop: ScreenUtils.scale(28),
    paddingRight: ScreenUtils.scale(20),
  },
  textProvider: {
    fontSize: 10,
    lineHeight: 15,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
  },
  iconSecure: {
    height: ScreenUtils.scale(24),
    width: ScreenUtils.scale(48),
    marginTop: ScreenUtils.scale(-5),
    marginLeft: ScreenUtils.scale(7),
  },
  buttonLayor: {
    paddingLeft: ScreenUtils.scale(38),
    paddingRight: ScreenUtils.scale(58),
    marginTop: ScreenUtils.scale(44),
  },
  buttonAddCrad: {
    justifyContent: "center",
    alignItems: "center",
    height: ScreenUtils.scale(48),
    width: "100%",
    backgroundColor: Themes.colors.primary,
    borderRadius: 24,
  },
  contentCardExsit: {
    paddingRight: ScreenUtils.scale(20),
    marginTop: ScreenUtils.scale(24),
  },
  itemCard: {
    height: ScreenUtils.scale(64),
    width: "100%",
    borderWidth: 1,
    borderRadius: 16,
    borderColor: Themes.colors.colGray20,
    paddingHorizontal: ScreenUtils.scale(16),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: ScreenUtils.scale(16),
  },
  iconCard: {
    height: ScreenUtils.scale(32),
    width: ScreenUtils.scale(48),
    marginRight: ScreenUtils.scale(16),
  },
  titleCard: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
    marginTop: ScreenUtils.scale(-5),
  },
  addCard: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.bold,
    color: Themes.colors.primary,
  },
  textNeed: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
    marginRight: ScreenUtils.scale(18),
  },
  flexModalAddCard: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  contentModalAddCard: {
    maxHeight: Dimensions.get("window").height * 0.8,
    backgroundColor: Themes.colors.white,
    paddingLeft: ScreenUtils.scale(20),
    paddingTop: ScreenUtils.scale(20),
    width: "100%",
    position: "absolute",
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    zIndex: 1,
  },
  titleAddCard: {
    fontSize: 18,
    lineHeight: 27,
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
  },
  buttonAddLayor: {
    paddingRight: ScreenUtils.scale(20),
    position: "absolute",
    bottom: 10,
    width: "100%",
  },
  contentHeaderPaypal: {
    flexDirection: "row",
    marginTop: ScreenUtils.scale(24),
  },
  logoPaypal: {
    height: ScreenUtils.scale(20),
    width: ScreenUtils.scale(17),
    marginRight: ScreenUtils.scale(10),
  },
  titlePaypal: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.bold,
    color: Themes.colors.coolGray60,
  },
  textEmailPaypal: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
    marginTop: ScreenUtils.scale(4),
    marginBottom: ScreenUtils.scale(8),
  },
  textPaypal: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
    marginBottom: ScreenUtils.scale(12),
  },
  switckPaypal: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "78%",
  },
  showMoreContent: {
    marginTop: ScreenUtils.scale(24),
  },
  itemMethodPaypal: {
    marginTop: ScreenUtils.scale(24),
    flexDirection: "row",
  },
  balanceText: {
    fontSize: 14,
    lineHeight: 21,
    ...Themes.font.regular,
    color: Themes.colors.textPrimary,
    marginTop: ScreenUtils.scale(5),
  },
  cardPaypal: {
    flexDirection: "row",
    marginLeft: ScreenUtils.scale(20),
  },
  buttonActive: {
    position: "absolute",
    top: ScreenUtils.scale(-5),
    left: 0,
    zIndex: 1,
  },
  textnumberCard: {
    fontSize: 12,
    lineHeight: 18,
    ...Themes.font.bold,
    color: Themes.colors.textPrimary,
  },
  textExchange: {
    fontSize: 12,
    lineHeight: 18,
    ...Themes.font.regular,
    color: Themes.colors.coolGray60,
  },
  textVnd: {
    fontSize: 12,
    lineHeight: 18,
    ...Themes.font.regular,
    color: Themes.colors.primary,
  },
  paddingButoon: {
    height: ScreenUtils.scale(120),
  },
  headerModalAdd: {
    height: ScreenUtils.scale(4),
    width: ScreenUtils.scale(48),
    backgroundColor: Themes.colors.white,
    borderRadius: 4,
  },
  headerModalAddLayor: {
    top: ScreenUtils.scale(-12),
    position: "absolute",
    width: "100%",
    alignItems: "center",
  },
  footer: {
    bottom: ScreenUtils.scale(20),
    position: "absolute",
    width: "100%",
    paddingHorizontal: ScreenUtils.scale(20),
  },
  currencyInput: {
    ...Themes.font.currency,
    fontSize: 20,
    lineHeight: 24,
    color: Themes.colors.coolGray60,
  },
  paymentMethodTitle: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
    color: Themes.colors.coolGray100,
    marginTop: ScreenUtils.scale(24),
    marginBottom: ScreenUtils.scale(12),
  },
  secureLabel: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: Themes.colors.coolGray60,
    marginTop: ScreenUtils.scale(4),
    marginLeft: ScreenUtils.scale(25),
  },
  bankSeparator: {
    marginTop: ScreenUtils.scale(12),
  },
  bankInfo: {
    marginLeft: ScreenUtils.scale(25),
  },
  paymentMethod: {
    backgroundColor: Themes.colors.colGray20,
  },
  icon: {
    marginTop: ScreenUtils.scale(4),
    marginLeft: ScreenUtils.scale(25),
  },
  tabBar: {
    backgroundColor: Themes.colors.white,
  },
  tabBarLabel: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
  },
  indicatorStyle: {
    backgroundColor: Themes.colors.primary,
    height: ScreenUtils.scale(4),
    borderTopLeftRadius: ScreenUtils.scale(4),
    borderTopRightRadius: ScreenUtils.scale(4),
    width: ScreenUtils.WIDTH_SCREEN / 3 - ScreenUtils.scale(32),
    marginHorizontal: ScreenUtils.scale(16),
  },
  paymentTitle: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: Themes.colors.coolGray60,
  },
  transactionFee: {
    marginLeft: ScreenUtils.scale(8),
    paddingHorizontal: ScreenUtils.scale(8),
    paddingVertical: ScreenUtils.scale(2),
    backgroundColor: Themes.colors.info10,
    borderRadius: ScreenUtils.scale(8),
  },
  paymentFee: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: Themes.colors.coolGray100,
  },
});
