export const CONSTANT = {
  LANGUAGES: {
    VI: "vi-VN",
    EN: "en-US",
    JA: "ja-JP",
    CN: "zh-CN",
    TW: "zh-TW",
  },
  REGION: {
    VN: "VN",
    US: "US",
  },
  TOKEN_STORAGE_KEY: {
    ACCESS_TOKEN: "access_token",
    REFRESH_TOKEN: "refresh_token",
    TOKEN_TYPE: "token_type",
    EXPRIES_IN: "expires_in",
    EXPRIES_AT: "expires_at",
    CURRENCY: "currency",
    WEBSITE_SHOPPING: "websiteShopping",
    FIRST_LAUNCH_APP: "first_launch_app",
    LANGUAGE: "language",
    ANONYMOUS_ID: "ANONYMOUS_ID",
    PRIMARY_CURRENCY: "PRIMARY_CURRENCY",
    REMEMBER_USER: "remember_user",
  },
  RELOAD_CONSTANTS: {
    RELOAD_PACKAGE_DELIVERY: "reload_package_delivery",
    RELOAD_ADDRESS: "reload_address",
  },
  WHATSAPP_LINK:
    "https://api.whatsapp.com/send/?phone=818060227335&text&app_absent=0",
  CURRENCY: {
    JA: "JPY",
    VND: "VND",
    USD: "USD",
    CNY: "CNY",
    TWD: "TWD",
  },
  TYPE_PICKER: {
    LANGUAGES: "Languages",
    CURRENCY: "Currency",
  },
  SHIPMENT_TYPE: {
    ECOMMERCE: "ECOMMERCE",
    GIFT: "GIFT",
  },
  REVOKE_TOKEN_ENDPOINT: "revocation",
  MENU_CONSTANT: {
    CREATE_SHIPMENT: "CREATE_SHIPMENT",
    CREATE_FROM_PAST: "CREATE_FROM_PAST",
    WAREHOUSE: "WAREHOUSE",
    SHIPMENT_MANAGE: "SHIPMENT_MANAGE",
    RATE_TIME: "RATE_TIME",
    ANALYTIC: "ANALYTIC",
  },
  WALLET_TYPE: {
    JPY_WALLET: "JPY_WALLET",
    PROMOTION_WALLET: "PROMOTION_WALLET",
    VND_WALLET: "VND_WALLET",
    USD_WALLET: "USD_WALLET",
  },
  RELOAD_ACTION: {
    RELOAD_PACKAGE: "RELOAD_PACKAGE",
    RELOAD_DETAIL_AUCTION: "RELOAD_DETAIL_AUCTION",
    RELOAD_WALLET: "RELOAD_WALLET",
    RELOAD_PAYMENT: "RELOAD_PAYMENT",
    RELOAD_TRANSACTION: "RELOAD_TRANSACTION",
  },
};
