export enum SCREENS {
  ROOT = "ROOT_NAVIGATION",
  LAUNCH_SCREEN = "LAUNCH_SCREEN",
  HOME_STACK = "HOME_STACK",
  HOME_SCREEN = "HOME_SCREEN",
  DETAIL_SCREEN = "DETAIL_SCREEN",
  INFO_SCREEN = "INFO_SCREEN",
  BOTTOM_TAB_NAVIGATION = "BOTTOM_TAB_NAVIGATOR",
  NOTIFICATION_STACK = "NOTIFICATION_STACK",
  CREATE_SHIPMENT_STACK = "CREATE_SHIPMENT_STACK",
  SHIPMENT_STACK = "SHIPMENT_STACK",
  MY_JANBOX_STACK = "MY_JANBOX_STACK",
}
