export const Images = {
  bannerDefault: require("../assets/banner-default.png"),
  bannerHomeDefault: require("../assets/banner/home_banner_default.png"),
  bannerHomeBrandDefault: require("../assets/banner/home_banner_brand_default.png"),
  icHome: require("../assets/icons/bottomTab/ic_home.png"),
  icHomeFill: require("../assets/icons/bottomTab/ic_home_fill.png"),
  icNotification: require("../assets/icons/bottomTab/ic_notification.png"),
  icNotificationFill: require("../assets/icons/bottomTab/ic_notification_fill.png"),
  icPackage: require("../assets/icons/bottomTab/ic_package.png"),
  icPackageFill: require("../assets/icons/bottomTab/ic_package_fill.png"),
  icMyJanbox: require("../assets/icons/bottomTab/ic_my_janbox.png"),
  icMyJanboxFill: require("../assets/icons/bottomTab/ic_my_janbox_fill.png"),
  lockedAccount: require("../assets/lockedAccount.png"),
  interface: require("../assets/interface.png"),
  easyPayment: require("../assets/easyPayment.png"),
  automated: require("../assets/automated.png"),
  deliveryTruck: require("../assets/delivery-truck.png"),
  imgDefautFirstTime: require("../assets/imgDefautFirstTime.png"),
  imgBackgroundDeliver: require("../assets/imgBackgroundDeliver.png"),
  ems: require("../assets/ems.png"),
  dhl: require("../assets/dhl.png"),
  fedEx: require("../assets/fedEx.png"),
  shield: require("../assets/shield.png"),
  noGift: require("../assets/noGift.png"),
  notificationNoResult: require("../assets/notification_noresult.png"),
  productDefault: require("../assets/default-product.png"),
  yourFavoriteItems1: require("../assets/home/YourFavoriteItem/ImageProduct.png"),
  shoe: require("../assets/shoe.png"),
  notificationSample: require("../assets/notification-sample.png"),
  icQuestion: require("../assets/icons/ic_question.png"),
  icCreateShipment: require("../assets/home/menu/create_shipment.png"),
  icCreateFromPast: require("../assets/home/menu/create_from_past.png"),
  icWarehouse: require("../assets/home/menu/warehouse.png"),
  icShipmentManage: require("../assets/home/menu/manage_shipment.png"),
  icRateTime: require("../assets/home/menu/rate_time.png"),
  icAnalytic: require("../assets/home/menu/analytic.png"),
  pickButton: require("../assets/button/picker.png"),
  icHoldPoint: require("../assets/icons/ic_hold_point.png"),
  icJGift: require("../assets/icons/ic_j_gift.png"),
  icJapan: require("../assets/icons/ic_japan.png"),
  icVietNam: require("../assets/icons/ic_vietnam.png"),
  icUSA: require("../assets/icons/ic_usa.png"),

  //region Deposit
  secure: require("../assets/deposit/secure.png"),
  VisaCardMethod: require("../assets/deposit/VisaCardMethod.png"),
  MasterCardMethod: require("../assets/deposit/MasterCardMethod.png"),
  maestro: require("../assets/deposit/maestro.png"),
  Amex: require("../assets/deposit/Amex.png"),
  logoPaypal: require("../assets/deposit/logoPaypal.png"),
  card: require("../assets/deposit/Card.png"),
  gmo: require("../assets/deposit/payment-gmo.png"),
  icAlipay: require("../assets/deposit/ic_alipay.png"),
  paypalMethod: require("../assets/deposit/paypal.png"),
  icPayMe: require("../assets/deposit/ic_pay_me.png"),
  icWithdrawSuccess: require("../assets/deposit/ic_withdraw_success.png"),

  //region Complaints
  noComplaintsImage: require("../assets/complaint.png"),
};

export const AnimationImages = {
  launchAnimation: require("../assets/lottie/launch-loader.json"),
};
