import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: ScreenUtils.scale(12),
    marginHorizontal: ScreenUtils.scale(16),
    borderTopColor: Themes.colors.colGray20,
  },
  headerView: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: ScreenUtils.scale(12),
  },
  balanceInfo: {
    flex: 1,
  },
  balanceTitle: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.coolGray60,
    fontWeight: "500",
    marginRight: ScreenUtils.scale(4),
  },
  balanceContent: {
    ...Themes.font.medium,
    fontSize: 14,
    lineHeight: 21,
    color: Themes.colors.coolGray100,
    fontWeight: "700",
  },
  exchangeTitle: {
    ...Themes.font.medium,
    fontSize: 10,
    lineHeight: 15,
    color: Themes.colors.coolGray60,
    fontWeight: "400",
  },
  exchangeContent: {
    ...Themes.font.medium,
    fontSize: 10,
    lineHeight: 15,
    color: Themes.colors.coolGray100,
    fontWeight: "400",
  },
  walletName: {
    ...Themes.font.medium,
    fontSize: 16,
    lineHeight: 24,
    color: Themes.colors.coolGray100,
    fontWeight: "500",
    marginHorizontal: ScreenUtils.scale(8),
  },
  depositBtn: {
    backgroundColor: Themes.colors.primary,
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(5),
    borderRadius: ScreenUtils.scale(14),
    marginRight: ScreenUtils.scale(16),
  },
  depositBtnText: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.white,
    fontWeight: "500",
  },
  primaryCurrency: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Themes.colors.info60,
    paddingHorizontal: ScreenUtils.scale(8),
    paddingVertical: ScreenUtils.scale(4),
    borderRadius: ScreenUtils.scale(16),
  },
  primaryCurrencyText: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.white,
    fontWeight: "500",
  },
  primaryCurrencyBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Themes.colors.white,
    paddingHorizontal: ScreenUtils.scale(8),
    paddingVertical: ScreenUtils.scale(4),
    borderRadius: ScreenUtils.scale(16),
    borderColor: Themes.colors.info60,
    borderWidth: StyleSheet.hairlineWidth,
  },
  primaryCurrencyBtnText: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.info60,
    fontWeight: "500",
  },
  withdrawBtn: {
    backgroundColor: Themes.colors.colGray10,
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(5),
    borderRadius: ScreenUtils.scale(14),
    marginRight: ScreenUtils.scale(16),
  },
  withdrawBtnText: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.coolGray60,
    fontWeight: "500",
  },
});
